.\" verbatim start and end macros.
.de Vb
.ft CW
.ps -1
.vs -1
.nf
.in +4n
.eo
..
.de Ve
.ft R
.ps
.vs
.fi
.in
.ec
..
.
.TH riscosehack 1
.
.SH NAME
.
.B riscosehack \(em a guide to riscose's source code
.
.SH ABSTRACT
.
.B riscose
is a fledging project, still feeling its way around.
It pulls together source from several other projects, including
.BR OSLib ,
and
.BR ARMulator ,
and configures and builds them under a single
.BR automake / autoconf
interface.
.BR riscose 's
internal architecture, the organisation of the source and coding
conventions, and the way it is configured and built are intended to be
described in this man page.
.
.SH NOTES
.
For the moment, there are just a series of notes in random order.
.
.
.SH BUGS
.
This man page is very incomplete.
.
.SH SEE ALSO
.
.BR riscose (1).
