/* os/basictrans.c
**
** See http://riscose.sourceforge.net/ for terms of distribution, and to
** pick up a later version of the software.
**
**   Emulation of the BASICTrans SWIs.
**
**   Template written by defmod (riscose version 1.00)
*/

#include <stdio.h>
#include <string.h>
#include <monty/monty.h>
#include <monty/mem.h>
#include "types.h"
#include "basictrans.h"
#include "rom/rom.h"

static char *basictrans_errors[] = {
  "Unknown setting of exception control",
  "Silly!",
  "No room do do this renumber",
  "Line numbers numbers larger than 65279 would be generated by this renumber",
  "No room",
  "Line too long",
  "Stopped",
  "Invalid LISTO option",
  "Invalid TWINO option",
  "",
  "Error control status not found on stack for RESTORE ERROR",
  "Missing incore name",
  "LIST/TWIN found line number reference",
  "HELP has no information on this keyword",
  "Incorrect in-core file description",
  "INSTALL cannot be used in a program",
  "No such mnemonic",
  "No such suffix on EQU",
  "Bad immediate constant",
  "Bad address offset",
  "Assembler limit reached",
  "Bad shift",
  "Bad register",
  "Duplicate register in multiply",
  "Missing =",
  "Missing = in FOR statement",
  "Mistake",
  "Missing ,",
  "Type mismatch: number needed",
  "Type mismatch: numeric variable needed",
  "Type mismatch: numeric array needed",
  "Type mismatch: string needed",
  "Type mismatch: string variable needed",
  "Type mismatch: string array needed",
  "Type mismatch: array needed",
  "Type mismatch between arrays",
  "Can't assign to array of this size",
  "Array type mismatch as parameter",
  "Can't SWAP arrays of different types",
  "Not in a function",
  "Too low a value for $<number>",
  "Missing """,
  "DIM() function needs an array",
  "No room to do matrix multiply with source(s) the same as destination",
  "Impossible dimension",
  "No end of dimension list )",
  "Bad DIM statement",
  "Can't DIM negative amount",
  "Arrays cannot be redimensioned",
  "No room for this DIM",
  "No room for this dimension",
  "Attempt to allocate insufficient memory",
  "Unreferenced local array in END=",
  "No room for program",
  "Items can only be made local in a function or procedure",
  "Not in a procedure",
  "Reference array incorrect",
  "Unknown array",
  "Unknown array in DIM() function",
  "Undimensioned array",
  "Subscript out of range",
  "Incorrect number of subscripts",
  "Syntax error",
  "Escape",
  "Division by zero",
  "String too long",
  "Number too big",
  "Number too big for arc Sine or arc Cosine",
  "Negative root",
  "Logarithm range",
  "Accuracy lost in Sine/Cosine/Tangent",
  "Exponent range",
  "Unknown or missing variable",
  "Can't use array reference here",
  "Missing )",
  "Missing (",
  "Missing ]",
  "Missing {",
  "Missing }",
  "Bad Hex",
  "Hex number too large",
  "Bad Binary",
  "No such function/procedure",
  "Bad call of function/procedure",
  "Arguments of function/procedure incorrect",
  "Invalid RETURN actual parameter",
  "Invalid array actual parameter",
  "Not in a FOR loop",
  "Can't match FOR",
  "Bad FOR control variable",
  "The step cannot be zero",
  "Missing TO",
  "No room for function/procedure call",
  "Not in a subroutine",
  "ON syntax",
  "ON range",
  "No such line",
  "Out of data",
  "DATA pointer not found on stack for RESTORE DATA",
  "Not in a REPEAT loop",
  "Too many nested structures",
  "Missing #",
  "Not in a WHILE loop",
  "Missing ENDCASE",
  "OF missing from CASE statement",
  "CASE..OF statement must be the last thing on a line",
  "Missing ENDIF",
  "Bad MOUSE variable",
  "Too many input expressions for SYS",
  "Too many output variables for SYS",
  "Can't install library",
  "Bad program used as function/procedure library",
  "No room for library"
};

void basictrans_swi_register_extra(void)
{

}

/* ------------------------------------------------------------------------
 * Function:      basictrans_help()
 *
 * Description:   Interpret, translate if required, and print HELP messages
 *
 * Input:         help_text - value of R0 on entry
 *                prog_name - value of R1 on entry
 *                lexical_table - value of R2 on entry
 *
 * Output:        unclaimed - value of R1 on exit (X version only)
 *
 * Returns:       R1 (non-X version only)
 *
 * Other notes:   Emulation of SWI 0x42C80.
 */

os_error *xbasictrans_help (char *help_text,
      char *prog_name,
      byte *lexical_table,
      osbool *unclaimed)
{
    *unclaimed = TRUE;

  return 0;
}

/* ------------------------------------------------------------------------
 * Function:      basictrans_error()
 *
 * Description:   Copy translated error string to buffer
 *
 * Input:         error_no - value of R0 on entry
 *                error_buffer - value of R1 on entry
 *
 * Other notes:   Emulation of SWI 0x42C81.
 */

os_error *xbasictrans_error(int error_no, char *error_buffer)
{
    static os_error standin = {
        0, "FIXME: what does the real thing do?"
    };

    /* FIXME: we should probably get these from a messages file. */
    if (error_no < 0 || error_no >= DIM(basictrans_errors)) {
        return &standin;
    }

    strcpy(error_buffer, basictrans_errors[error_no]);

    return NULL;
}

/* ------------------------------------------------------------------------
 * Function:      basictrans_message()
 *
 * Description:   Translate and print miscellaneous message
 *
 * Input:         message_no - value of R0 on entry
 *                arg0 - value of R1 on entry
 *                arg1 - value of R2 on entry
 *                arg2 - value of R3 on entry
 *
 * Other notes:   Emulation of SWI 0x42C82.
 */

os_error *xbasictrans_message (int message_no,
      int arg0,
      int arg1,
      int arg2)
{
    return ERR_BASICTRANS_UNKNOWN_OPERATION();
}
