#! /bin/sh

set -e
set -x

r=../src/riscose

# should fail if no arguments given.
set +e
$r >tmp.1 2>tmp.2
e=$?
set -e
test $e -eq 1
test `wc -c <tmp.1` -eq 0
test `wc -l <tmp.2` -eq 1
grep 'no risc os executable specified' tmp.2 >/dev/null

# check version number is correct and that long arguments are working.
for a in -v --version; do
    set +e
    $r $a >tmp.1 2>tmp.2
    e=$?
    set -e
    test $e -eq 0
    test `wc -l <tmp.1` -eq 1
    test `wc -c <tmp.2` -eq 0
    grep "version $VERSION"\$ tmp.1 >/dev/null
done

# help option works.
set +e
$r -h >tmp.1 2>tmp.2
e=$?
set -e
test $e -eq 0
test `wc -l <tmp.1` -gt 5
test `wc -c <tmp.2` -eq 0
sed 1q tmp.1 | grep 'usage: riscose ' >/dev/null
awk '/^    -/ {i++} END {i < 5}' tmp.1

rm tmp.1 tmp.2
