SRCDIR = /home/mattbee/Projects/riscose/riscose/src
CC      = gcc
CFLAGS  = -Wall -I$(SRCDIR)
# -O3 -funroll-loops
LDFLAGS = 
# -lefence

include $(SRCDIR)/Makefile.options

%.o:	%.c mem.h arm.h
	$(CC) $(CFLAGS) -g3 -c -o $@ $<
