---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Install required packages
        run: |
          sudo apt-get -y install autoconf libgdbm-dev

      - name: Run minimal compile
        run: |
          autoreconf -if
          ./configure
          make

      - name: Quick test
        run: |
          wget https://riscose.sourceforge.net/grep.gz
          gzip -d grep.gz
          ./src/riscose --romimage=src/rom/romimage grep --version

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            src/riscose
            src/rom/romimage
